In [1]:
pip install opencv-python


Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
!pip install opencv-python


In [4]:
import os
import cv2
import numpy as np
#from tensorflow.keras.utils import to_categorical
import tensorflow as tf


In [6]:
from tensorflow.compat.v1.losses import sparse_softmax_cross_entropy

In [7]:
pip install tensorflow-gpu


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\harsh\AppData\Local\Temp\pip-install-b101aeik\tensorflow-gpu_58ba4afd49114a94868fea9886fb8a9b\setup.py", line 37, in <module>
          raise Exception(TF_REMOVAL_WARNING)
      Exception:
      
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
ERROR: Could not buil


  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached python_version-0.0.2-py2.py3-none-any.whl (3.4 kB)
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu


In [8]:
pip install --upgrade tensorflow


Note: you may need to restart the kernel to use updated packages.


In [9]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))


Num GPUs Available:  0


In [ ]:
def load_and_preprocess_data(data_path):
    images = []
    labels = []

    class_names = os.listdir(data_path)

    # Create a mapping from class names to integer labels
    class_to_index = {class_name: idx for idx, class_name in enumerate(class_names)}

    for symbol_class in class_names:
        class_path = os.path.join(data_path, symbol_class)
        for image_file in os.listdir(class_path):
            image_path = os.path.join(class_path, image_file)
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            image = cv2.resize(image, (32, 32))  # Resize to a consistent size
            image = image / 255.0  # Normalize pixel values
            images.append(image)
            labels.append(class_to_index[symbol_class])

    images = np.array(images)
    
    # Use to_categorical from tensorflow.keras.utils.np_utils
    labels = tf.one_hot(labels, depth=len(class_names))

    return images, labels

In [ ]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [ ]:
def build_symbol_detection_model(input_shape, num_classes):
    model = Sequential()
    model.add(Conv2D(32, (3, 3), activation='relu', input_shape=input_shape))
    model.add(MaxPooling2D((2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))  # Softmax for multi-class classification

    # Modify the loss function to 'categorical_crossentropy'
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
images, labels = load_and_preprocess_data('E:\Enhancing-Accessibility-for-People-with-Disabilities\data\extracted_images')


In [ ]:
input_shape = (32, 32, 1)  # Assuming images are grayscale
num_classes = len(os.listdir('E:\Enhancing-Accessibility-for-People-with-Disabilities\data\extracted_images'))

In [ ]:
num_classes

82

In [ ]:
images.shape

(375974, 32, 32)

In [ ]:
labels=labels.numpy()

In [ ]:
labels.shape

(375974, 82)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

model = build_symbol_detection_model(input_shape, num_classes)
#model = build_symbol_detection_model(input_shape, num_classes=len(class_names))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))




Epoch 1/10


9400/9400 [==============================] - 218s 23ms/step - loss: 0.6636 - accuracy: 0.8205 - val_loss: 0.3912 - val_accuracy: 0.8879
Epoch 2/10
9400/9400 [==============================] - 181s 19ms/step - loss: 0.3323 - accuracy: 0.9018 - val_loss: 0.2801 - val_accuracy: 0.9181
Epoch 3/10
9400/9400 [==============================] - 125s 13ms/step - loss: 0.2539 - accuracy: 0.9232 - val_loss: 0.2400 - val_accuracy: 0.9290
Epoch 4/10
9400/9400 [==============================] - 128s 14ms/step - loss: 0.2071 - accuracy: 0.9363 - val_loss: 0.2125 - val_accuracy: 0.9350
Epoch 5/10
9400/9400 [==============================] - 126s 13ms/step - loss: 0.1747 - accuracy: 0.9456 - val_loss: 0.1911 - val_accuracy: 0.9408
Epoch 6/10
9400/9400 [==============================] - 125s 13ms/step - loss: 0.1498 - accuracy: 0.9525 - val_loss: 0.1673 - val_accuracy: 0.9483
Epoch 7/10
9400/9400 [==============================] - 126s 13ms/step - loss: 0.1322 - accuracy: 0.9578 - val_lo

In [ ]:
i=0
for symbol_class in range(16, len(os.listdir('E:\Enhancing-Accessibility-for-People-with-Disabilities\data\extracted_images'))):
        print(os.listdir('E:\Enhancing-Accessibility-for-People-with-Disabilities\data\extracted_images')[symbol_class])
        

=
A
alpha
ascii_124
b
beta
C
cos
d
Delta
div
e
exists
f
forall
forward_slash
G
gamma
geq
gt
H
i
in
infty
int
j
k
l
lambda
ldots
leq
lim
log
lt
M
mu
N
neq
o
p
phi
pi
pm
prime
q
R
rightarrow
S
sigma
sin
sqrt
sum
T
tan
theta
times
u
v
w
X
y
z
[
]
{
}


In [ ]:
labels

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [ ]:
def get_symbol_description(predicted_class):
    # Map numeric classes to corresponding descriptions
    class_descriptions = {
        0: 'exclamatory mark',
        1: 'Opening round bracket',
        2: 'closing round bracket',
        3: 'Plus',
        4: 'Comma',
        5: 'minus',
        6: 'Zero',
        7: 'One',
        8: 'Two',
        9: 'Three',
        10: 'Four',
        11: 'Five',
        12: 'Six',
        13: 'Seven',
        14: 'Eight',
        15:  'Nine',
        16: 'Equal to',
        17: 'a',
        18: 'alpha',
        19: 'ascii',
        20: 'b',
        70:  'Theta',
        21: 'beta',
        22: 'c',
        23: 'cos',
        24: 'd',
        25: 'delta',
        26: 'devide by',
        27: 'e',
        28: 'there exists',
        29: 'f',
        30: 'for all',
        31: 'forward slash',
        32: 'g',
        33: 'gamma'
        # Add more descriptions as needed
    }

    # Return the description for the predicted class, or a default if not found
    return class_descriptions.get(predicted_class, 'Unknown Symbol')


In [ ]:
# Example using gTTS (Google Text-to-Speech) library
from gtts import gTTS
import IPython.display as ipd

def generate_audio_description(text):
    tts = gTTS(text=text, lang='en', slow=False)
    tts.save('audio_description.mp3')
    ipd.Audio('audio_description.mp3')


In [ ]:
def detect_and_describe_symbols(image_path):
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    image = cv2.resize(image, (32, 32))
    image = image / 255.0
    image = np.expand_dims(image, axis=0)

    prediction = model.predict(image)
    predicted_class = np.argmax(prediction)
    
    #predicted_class=predicted_class-6
    symbol_description = get_symbol_description(predicted_class)
    generate_audio_description(symbol_description)

    return predicted_class


In [ ]:
import IPython.display as ipd

In [ ]:
def detect_and_describe_symbols(symbol_image):
    image = cv2.resize(symbol_image, (32, 32))
    image = image / 255.0
    image = np.expand_dims(image, axis=0)

    prediction = model.predict(image)
    predicted_class = np.argmax(prediction)
    symbol_description = get_symbol_description(predicted_class)
    
    return predicted_class, symbol_description


In [ ]:
def detect_and_describe_formula(formula_image_path):
    # Split the formula image into individual symbols
    symbol_images = split_formula_into_symbols(formula_image_path)

    # Detect and describe each symbol
    symbols = []
    for symbol_image in symbol_images:
        predicted_class, symbol_description = detect_and_describe_symbols(symbol_image)
        symbols.append((predicted_class, symbol_description))
        print(f"Predicted Class: {predicted_class}, Description: {symbol_description}")

    # Combine individual symbol descriptions into a formula description
    formula_description = ' '.join([symbol[1] for symbol in symbols])

    # Generate audio description for the entire formula
    generate_audio_description(formula_description)

    return formula_description


In [ ]:
def split_formula_into_symbols(formula_image_path):
    # Load the formula image
    formula_image = cv2.imread(formula_image_path, cv2.IMREAD_GRAYSCALE)
    
    # Threshold the image to create a binary image
    _, binary_image = cv2.threshold(formula_image, 128, 255, cv2.THRESH_BINARY_INV)

    # Find contours in the binary image
    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Sort contours by their x-coordinate to get symbols from left to right
    contours = sorted(contours, key=lambda x: cv2.boundingRect(x)[0])

    # Extract individual symbols
    symbols = []
    for contour in contours:
        x, y, w, h = cv2.boundingRect(contour)
        
        # Extract individual symbols based on bounding rectangles
        symbol_image = formula_image[y:y+h, x:x+w]
        symbols.append(symbol_image)

    return symbols

In [ ]:
formula_image_path = "inp.jpg"
detected_symbols = split_formula_into_symbols(formula_image_path)
detect_and_describe_formula(formula_image_path)

1/1 [==============================] - 1s 692ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 20ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 27ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 32ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 31ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 30ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 37ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 35ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 30ms/step
Predicted Class: 52, Description: Unknown Symbol
1/1 [==============================] - 0s 50ms/step
Predicted Class: 52, Description: Unkn

'Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown Symbol Unknown S

In [ ]:
detected_symbols

[array([[127, 129, 130],
        [127, 128, 129],
        [127, 127, 128],
        [127, 126, 127],
        [127, 126, 127],
        [126, 127, 128],
        [126, 128, 129],
        [126, 128, 130],
        [127, 127, 128]], dtype=uint8),
 array([[128, 128],
        [127, 128]], dtype=uint8),
 array([[132, 131, 129, 128, 127, 127, 127, 128, 129, 129, 130, 131, 132,
         132, 133, 133, 133, 134],
        [130, 129, 128, 126, 126, 125, 126, 126, 127, 128, 129, 130, 131,
         132, 133, 133, 134, 134],
        [129, 128, 126, 125, 124, 124, 124, 125, 126, 127, 128, 129, 131,
         132, 133, 133, 133, 133],
        [128, 127, 126, 124, 124, 123, 124, 124, 126, 127, 128, 129, 131,
         132, 133, 134, 133, 133],
        [128, 127, 126, 124, 124, 123, 124, 124, 126, 127, 128, 130, 131,
         133, 134, 135, 134, 134],
        [128, 127, 126, 125, 124, 124, 124, 124, 126, 127, 128, 130, 132,
         134, 135, 136, 135, 135],
        [130, 128, 126, 124, 123, 124, 127, 128, 12

In [ ]:
image = cv2.resize('image.jpg', (32, 32))
image = image / 255.0
image = np.expand_dims(image, axis=0)

prediction = model.predict(image)

error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'


In [ ]:
image_path = 'image.jpg'
detect_and_describe_formula(image_path)

1/1 [==============================] - 0s 41ms/step
Predicted Class: 35, Description: Unknown Symbol
1/1 [==============================] - 0s 33ms/step
Predicted Class: 24, Description: d


'Unknown Symbol d'